version: '3'

services:
  yarn:
    build:
      context: ./
      dockerfile: yarn.Dockerfile
    working_dir: /workspace
    volumes:
      - ./../:/workspace
    entrypoint:
      - yarn

  app:
    build:
      context: ./
      dockerfile: app.Dockerfile
    working_dir: /var/www
    volumes:
      - ./../:/var/www
    environment:
      DB_PORT: 3306
      DB_HOST: database
    links:
      - redis:redis

  web:
    build:
      context: ./
      dockerfile: web.Dockerfile
    working_dir: /var/www
    volumes:
      - ./../:/var/www
    ports:
      - ${NGINX_SERVER_PORT}:80
    extra_hosts:
      ${COMPOSE_PROJECT_NAME}.127.0.0.1.xip.io: 127.0.0.1
      ${COMPOSE_PROJECT_NAME}.127.0.0.1.nip.io: 127.0.0.1

  database:
    image: mysql:5.7
    volumes:
      - ./dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - ${MYSQL_SERVER_PORT}:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - ${PHPMYADMIN_SERVER_PORT}:80
    links:
      - database:homestead
    environment:
      MYSQL_ROOT_PASSWORD: secret
      PMA_HOST: homestead
    extra_hosts:
      ${COMPOSE_PROJECT_NAME}.127.0.0.1.xip.io: 127.0.0.1
      ${COMPOSE_PROJECT_NAME}.127.0.0.1.nip.io: 127.0.0.1

  redis:
    build:
      context: ./
      dockerfile: redis.Dockerfile

volumes:
  dbdata:
